name: scm_geosmart
channels:
  - conda-forge
dependencies:
  - python=3.10
  - sphinxcontrib-bibtex
  - jupyter-book=0.13
  - jupytext
  - numpy
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - rasterio
  - fiona
platforms:
  - linux-64
  - osx-64
